modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"

issueTrackerURL = "https://github.com/najoan125/KoreanPatch-multiLoader/issues"

[[mods]]
modId = "${mod_id}"

displayName = "${mod_name}"

version = "${version}"

logoFile = "icon.png"

authors = "${mod_author}"
credits = """

    Contributors: ${credits}"""

description = '''
${description}
'''

modUrl = "https://modrinth.com/mod/korean-chat-patch"
displayURL = "https://modrinth.com/mod/korean-chat-patch"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_version_range}"
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "CLIENT" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"