# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
mod_version=1.7.1
group=com.hyfata
java_version=21

# Common
minecraft_version=1.21.5
mod_name=Korean Patch
mod_author=Najoan
mod_id=koreanpatch
license=LGPL-3.0
credits=Shihyeon
description=It allows you to input Hangul naturally, and the Hangul input state does not interfere with other keys.
minecraft_version_range=[1.21.5, 1.22)
fabric_version_range=>=1.21.5 <1.22

# Common
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830

# Cloth Config
# https://linkie.shedaniel.me/dependencies
cloth_config=18.0.145

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.119.5+1.21.5
fabric_loader_version=0.16.10

# Fabric dependencies(CompileOnly)
# https://modrinth.com/mod/modmenu
modmenu_version = 14.0.0-rc.2
# https://modrinth.com/mod/command-block-ide
command_block_ide_version = 0.4.11
# https://modrinth.com/mod/bettercommandblockui
better_command_block_ui_version = HkltAat3
# https://modrinth.com/mod/easy-anvils
easy_anvils_version_fabric = cgAd1uKH
easy_anvils_version_neo = znA9vlFD
# https://modrinth.com/mod/axiom
axiom_version = Ww9uleCZ
# https://modrinth.com/mod/xaeros-minimap
xaeros_minimap_fabric = tYtr1STe
xaeros_minimap_neo = se44ujZ0
# https://modrinth.com/mod/xaeros-world-map
xaeros_world_map_fabric = fh7IHLqi
xaeros_world_map_neo = 8rYFL1jh

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.5.2-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
