# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
mod_version=1.9.6
group=com.hyfata
java_version=16

# Common
minecraft_version=1.17.1
mod_name=Korean Patch
mod_author=Najoan
mod_id=koreanpatch
license=LGPL-3.0
credits=Shihyeon
description=It allows you to input Hangul naturally, and the Hangul input state does not interfere with other keys.
minecraft_version_range=[1.17, 1.18)
fabric_version_range=>=1.17 <1.18

# ParchmentMC
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.17.1
parchment_version=2021.12.12

# Cloth Config
# https://linkie.shedaniel.me/dependencies
cloth_config=5.3.63

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version=0.16.5
fabric_version=0.46.1+1.17

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=37.1.1
forge_loader_version_range=[37,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# mod dependencies(CompileOnly)
# https://modrinth.com/mod/modmenu
modmenu_version = 2.0.17
# https://modrinth.com/mod/command-block-ide
command_block_ide_version = 0.2.1
# https://modrinth.com/mod/xaeros-minimap
xaeros_minimap_fabric = VuH8AYM3
xaeros_minimap_forge = yqp93Q5R
# https://modrinth.com/mod/xaeros-world-map
xaeros_world_map_fabric = X5l3pEeo
xaeros_world_map_forge = pJR2Fqwm
# https://modrinth.com/mod/rei
rei_fabric = APMWQGer
rei_forge = LBM0GUQk