# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
mod_version=1.8.1
group=com.hyfata
java_version=21

# Common
minecraft_version=1.21.3
mod_name=Korean Patch
mod_author=Najoan
mod_id=koreanpatch
license=LGPL-3.0
credits=Shihyeon
description=It allows you to input Hangul naturally, and the Hangul input state does not interfere with other keys.
minecraft_version_range=[1.21.2, 1.21.5)
fabric_version_range=>=1.21.2 <1.21.5

# Common
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.3-20241023.131943

# Cloth Config
# https://linkie.shedaniel.me/dependencies
cloth_config=16.0.143

# Yet Another Config Lib
# https://modrinth.com/mod/yacl
yacl_version=3.6.6+1.21.3

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.114.0+1.21.3
fabric_loader_version=0.16.10

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.3.3-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# mod dependencies(CompileOnly)
# https://modrinth.com/mod/modmenu
modmenu_version = 12.0.0-beta.1
# https://modrinth.com/mod/command-block-ide
command_block_ide_version = 0.4.8
# https://modrinth.com/mod/bettercommandblockui
better_command_block_ui_version = XCUcnTCS
# https://modrinth.com/mod/easy-anvils
easy_anvils_version_fabric = 8VYsDvN0
easy_anvils_version_neo = eWDGOU0o
# https://modrinth.com/mod/axiom
axiom_version = jMEXGFSh
# https://modrinth.com/mod/xaeros-minimap
xaeros_minimap_fabric = yIxg4FxZ
xaeros_minimap_neo = ADp3oSKf
# https://modrinth.com/mod/xaeros-world-map
xaeros_world_map_fabric = 2O7E8f9x
xaeros_world_map_neo = V7jkqREe
# https://modrinth.com/mod/rei
rei_fabric = ZuAv0Xt4
rei_neo = V5Z90SQ7