modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

issueTrackerURL = "https://github.com/najoan125/KoreanPatch-multiLoader/issues"

[[mods]]
modId = "${mod_id}"

displayName = "${mod_name}"

version = "${version}"

logoFile = "assets/koreanpatch/icon.png"

authors = "${mod_author}"
credits = """

    Contributors: ${credits}"""

description = '''
${description}
'''

modUrl = "https://modrinth.com/mod/korean-chat-patch"
displayURL = "https://modrinth.com/mod/korean-chat-patch"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${neoforge_version},)"
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "CLIENT" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
