plugins {
    id 'multiloader-loader'
    id 'net.neoforged.gradle.userdev'
}

def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
if (at.exists()) {
    minecraft.accessTransformers.file at
}

runs {
    configureEach {
        modSource project.sourceSets.main
    }
    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }
    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    api "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config}"
    compileOnly "maven.modrinth:easy-anvils:${project.easy_anvils_version_neo}"
    compileOnly "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_neo}"
    compileOnly "maven.modrinth:xaeros-world-map:${project.xaeros_world_map_neo}"
    compileOnly "maven.modrinth:rei:${project.rei_neo}"
}

compileJava.options.encoding = 'UTF-8'
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}