plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    api "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config}"
    compileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge"
    compileOnly "maven.modrinth:easy-anvils:${project.easy_anvils_version_neo}"
    compileOnly "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_neo}"
    compileOnly "maven.modrinth:xaeros-world-map:${project.xaeros_world_map_neo}"
    compileOnly "maven.modrinth:rei:${project.rei_neo}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}